name: coverage

on: ['push', 'pull_request']

jobs:
    coverage:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: ['8.4', '8.5']

        name: Coverage - P${{ matrix.php }}

        defaults:
            run:
                working-directory: mail-log-statamic

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    path: mail-log-statamic

            -   name: Checkout Laravel mail log
                uses: actions/checkout@v4
                with:
                    repository: BobWez98/mail-log-laravel
                    path: mail-log-laravel

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, xdebug
                    coverage: xdebug

            -   name: Install dependencies
                run: composer install

            -   name: Coverage
                run: composer coverage
